version: '3.7'

services:
  db:
    image: mysql
    ports:
      - "3306"
    env_file: .env
    environment:
      MYSQL_DATABASE: "moviedb"
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "root"
    
  django:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./front-end
    command: ["npm", "run", "build"]
    ports:
      - "3000:3000"