version: '1'

services:
  db:
    image: mysql
    ports:
      - "3306"

  django:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./front-end
    command: ["npm", "run", "build"]
    ports:
      - "3000:3000"