FROM ubuntu:18.04

MAINTAINER Will Li

ENV HOMEDIR = /home/ubuntu
ENV PROJECTDIR = /home/ubuntu/MRS
ENV FRONTENDDIR = /home/ubuntu/MRS/front-end

# Copy forntend files
WORKDIR $FRONTENDDIR
COPY ./package.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "build"]
