export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";


export const GET_MOVIE_START = "GET_MOVIE_START";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_FAIL = "GET_MOVIE_FAIL";


export const GET_MOVIE_DETAIL_START = "GET_MOVIE_DETAIL_START";
export const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_DETAIL_SUCCESS";
export const GET_MOVIE_DETAIL_FAIL = "GET_MOVIE_DETAIL_FAIL";


export const GET_GENRE_START = "GET_GENRE_START";
export const GET_GENRE_SUCCESS = "GET_GENRE_SUCCESS";
export const GET_GENRE_FAIL = "GET_GENRE_FAIL";


export const USER_MOVIE_ACTION = "USER_MOVIE_ACTION";
export const USER_MOVIE_REMOVE = "USER_MOVIE_REMOVE";
export const USER_MOVIE_SUCCESS = "USER_MOVIE_SUCCESS";
export const USER_MOVIE_FAIL = "USER_MOVIE_FAIL";